print('This is a madlib game.')
print(' What is your favorite color')
color = input()
print('What is your preferred mode of transportation?')
transport = input()
print('What is your favorite holiday?')
holiday = input()
print('You will receive a ' + color + ' ' + transport + ' on ' + holiday)
