# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flut',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 22, 0, 3, 500060, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
