# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0002_flut_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flut',
            name='user_name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
